Repository HaRu-Developers/haru-springboot-api, pull requests merged in 2025-07, with the labels that each got.

#8 feat/#7: Users 엔티티 생성
  .gitignore
  src/main/java/com/haru/api/HaruApiApplication.java
  src/main/java/com/haru/api/domain/user/entity/Users.java
  src/main/java/com/haru/api/domain/user/entity/enums/Status.java
  src/main/java/com/haru/api/global/apiPayload/ApiResponse.java
  src/main/java/com/haru/api/global/apiPayload/code/BaseCode.java
  src/main/java/com/haru/api/global/apiPayload/code/BaseErrorCode.java
  src/main/java/com/haru/api/global/apiPayload/code/ErrorReasonDTO.java
  src/main/java/com/haru/api/global/apiPayload/code/ReasonDTO.java
  src/main/java/com/haru/api/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/haru/api/global/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/haru/api/global/apiPayload/exception/ExceptionAdvice.java
  src/main/java/com/haru/api/global/apiPayload/exception/GeneralException.java
  src/main/java/com/haru/api/global/apiPayload/exception/handler/TempHandler.java
  src/main/java/com/haru/api/global/common/entity/BaseEntity.java
  src/main/java/com/haru/apiPayload/exception/handler/TempHandler.java
  src/main/resources/application.yml
Labels: ✨ Feature

#13 feat/#12: 회원가입 api 구현 완료
  build.gradle
  src/main/java/com/haru/api/HaruApiApplication.java
  src/main/java/com/haru/api/domain/user/controller/UserController.java
  src/main/java/com/haru/api/domain/user/converter/UserConverter.java
  src/main/java/com/haru/api/domain/user/dto/UserRequestDTO.java
  src/main/java/com/haru/api/domain/user/dto/UserResponseDTO.java
  src/main/java/com/haru/api/domain/user/entity/Users.java
  src/main/java/com/haru/api/domain/user/repository/UserRepository.java
  src/main/java/com/haru/api/domain/user/service/UserCommandService.java
  src/main/java/com/haru/api/domain/user/service/UserCommandServiceImpl.java
  src/main/java/com/haru/api/global/config/SecurityConfig.java
Labels: ✨ Feature

#25 Feat/#24 jwt토큰 생성 및 Spring Security를 활용한 토큰 검증(인가 처리) 구현 완료, access token갱신과 로그아웃 api 구현 완료
  .github/workflows/ci.yml
  build.gradle
  src/main/java/com/haru/api/domain/user/controller/UserController.java
  src/main/java/com/haru/api/domain/user/converter/UserConverter.java
  src/main/java/com/haru/api/domain/user/dto/UserResponseDTO.java
  src/main/java/com/haru/api/domain/user/repository/UserRepository.java
  src/main/java/com/haru/api/domain/user/security/jwt/CustomExpiredJwtException.java
  src/main/java/com/haru/api/domain/user/security/jwt/CustomJwtException.java
  src/main/java/com/haru/api/domain/user/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/haru/api/domain/user/security/jwt/JwtUtils.java
  src/main/java/com/haru/api/domain/user/security/jwt/SecurityUtil.java
  src/main/java/com/haru/api/domain/user/service/UserCommandService.java
  src/main/java/com/haru/api/domain/user/service/UserCommandServiceImpl.java
  src/main/java/com/haru/api/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/haru/api/global/config/RedisConfig.java
Labels: ✨ Feature

#37 deploy 1.1 - 회의록 생성 API 추가
  src/main/java/com/haru/api/domain/meeting/controller/MeetingController.java
  src/main/java/com/haru/api/domain/meeting/converter/MeetingConverter.java
  src/main/java/com/haru/api/domain/meeting/dto/MeetingRequestDTO.java
  src/main/java/com/haru/api/domain/meeting/dto/MeetingResponseDTO.java
  src/main/java/com/haru/api/domain/meeting/entity/Meetings.java
  src/main/java/com/haru/api/domain/meeting/repository/MeetingRepository.java
  src/main/java/com/haru/api/domain/meeting/service/MeetingService.java
  src/main/java/com/haru/api/domain/meeting/service/MeetingServiceImpl.java
  src/main/java/com/haru/api/global/apiPayload/code/status/ErrorStatus.java
Labels: 🌏 Deploy

#63 feat/#61: 팀분위기 트래커 패키지 구조 적용 및 엔티티 작성
  src/main/java/com/haru/api/domain/moodTracker/controller/MoodTrackerController.java
  src/main/java/com/haru/api/domain/moodTracker/converter/MoodTrackerConverter.java
  src/main/java/com/haru/api/domain/moodTracker/dto/MoodTrackerReqeustDTO.java
  src/main/java/com/haru/api/domain/moodTracker/dto/MoodTrackerResponseDTO.java
  src/main/java/com/haru/api/domain/moodTracker/entity/MoodTracker.java
  src/main/java/com/haru/api/domain/moodTracker/entity/enums/MoodTrackerVisibility.java
Labels: ✨ Feature

#72 feat/#67 meeting update delete api
  src/main/java/com/haru/api/domain/meeting/controller/MeetingController.java
  src/main/java/com/haru/api/domain/meeting/dto/MeetingRequestDTO.java
  src/main/java/com/haru/api/domain/meeting/entity/Meetings.java
  src/main/java/com/haru/api/domain/meeting/service/MeetingCommandService.java
  src/main/java/com/haru/api/domain/meeting/service/MeetingCommandServiceImpl.java
  src/main/java/com/haru/api/domain/meeting/service/MeetingQueryService.java
  src/main/java/com/haru/api/domain/meeting/service/MeetingQueryServiceImpl.java
  src/main/java/com/haru/api/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/haru/api/global/apiPayload/exception/handler/MeetingHandler.java
Labels: ✨ Feature, 🔨 Refactor

#84 feat/#59: 팀 분위기 트래커 설문 링크 전송 & 설문 답변 API 구현
  build.gradle
  src/main/java/com/haru/api/domain/moodTracker/controller/MoodTrackerController.java
  src/main/java/com/haru/api/domain/moodTracker/converter/MoodTrackerConverter.java
  src/main/java/com/haru/api/domain/moodTracker/dto/MoodTrackerRequestDTO.java
  src/main/java/com/haru/api/domain/moodTracker/entity/MultipleChoiceAnswer.java
  src/main/java/com/haru/api/domain/moodTracker/entity/SubjectiveAnswer.java
  src/main/java/com/haru/api/domain/moodTracker/repository/CheckboxChoiceAnswerRepository.java
  src/main/java/com/haru/api/domain/moodTracker/repository/MultipleChoiceAnswerRepository.java
  src/main/java/com/haru/api/domain/moodTracker/repository/SubjectiveAnswerRepository.java
  src/main/java/com/haru/api/domain/moodTracker/repository/SurveyQuestionRepository.java
  src/main/java/com/haru/api/domain/moodTracker/service/MoodTrackerCommandService.java
  src/main/java/com/haru/api/domain/moodTracker/service/MoodTrackerCommandServiceImpl.java
  src/main/java/com/haru/api/domain/moodTracker/service/MoodTrackerMailService.java
  src/main/java/com/haru/api/domain/moodTracker/service/MoodTrackerMailServiceImpl.java
  src/main/java/com/haru/api/domain/userWorkspace/repository/UserWorkspaceRepository.java
  src/main/java/com/haru/api/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/haru/api/global/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/haru/api/global/config/MailConfig.java
  src/main/java/com/haru/api/infra/mail/EmailSender.java
  src/main/java/com/haru/api/infra/mail/SmtpEmailSender.java
  src/main/java/com/haru/api/infra/mail/handler/MailHandler.java
  src/test/java/com/haru/api/config/MailTestConfig.java
Labels: ✨ Feature

#87 refactor/#80: mood tracker 7/22 회의 내용 관련 리팩토링
  src/main/java/com/haru/api/domain/moodTracker/controller/MoodTrackerController.java
  src/main/java/com/haru/api/domain/moodTracker/converter/MoodTrackerConverter.java
  src/main/java/com/haru/api/domain/moodTracker/dto/MoodTrackerResponseDTO.java
  src/main/java/com/haru/api/domain/moodTracker/service/MoodTrackerCommandServiceImpl.java
  src/main/java/com/haru/api/domain/moodTracker/service/MoodTrackerMailServiceImpl.java
  src/main/java/com/haru/api/domain/moodTracker/service/MoodTrackerQueryService.java
  src/main/java/com/haru/api/domain/moodTracker/service/MoodTrackerQueryServiceImpl.java
  src/main/java/com/haru/api/domain/workspace/repository/WorkspaceRepository.java
Labels: ✨ Feature

#88 feat/#78: ai question create implement
  .gitignore
  src/main/java/com/haru/api/domain/user/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/haru/api/global/config/ObjectMapperConfig.java
  src/main/java/com/haru/api/global/config/WebClientConfig.java
  src/main/java/com/haru/api/global/config/WebSocketConfig.java
  src/main/java/com/haru/api/infra/api/client/ChatGPTClient.java
  src/main/java/com/haru/api/infra/api/client/FastApiClient.java
  src/main/java/com/haru/api/infra/api/controller/APIController.java
  src/main/java/com/haru/api/infra/api/converter/SpeechSegmentConverter.java
  src/main/java/com/haru/api/infra/api/dto/AIQuestionRequest.java
  src/main/java/com/haru/api/infra/api/dto/AIQuestionResponse.java
  src/main/java/com/haru/api/infra/api/dto/OpenAIResponse.java
  src/main/java/com/haru/api/infra/api/dto/SpeechSegmentResponseDTO.java
  src/main/java/com/haru/api/infra/api/dto/SttResponseDTO.java
  src/main/java/com/haru/api/infra/api/dto/WebSocketMessage.java
  src/main/java/com/haru/api/infra/api/entity/SpeechSegment.java
  src/main/java/com/haru/api/infra/api/repository/SpeechSegmentRepository.java
  src/main/java/com/haru/api/infra/websocket/AudioProcessingQueue.java
  src/main/java/com/haru/api/infra/websocket/AudioSessionBuffer.java
  src/main/java/com/haru/api/infra/websocket/AudioWebSocketHandler.java
  src/main/java/com/haru/api/infra/websocket/FastApiClient.java
  src/test/resources/application-test.yml
Labels: ✨ Feature

#90 feat/#86: ID 해싱 유틸 추가 및 팀분위기 트래커에 적용
  build.gradle
  src/main/java/com/haru/api/domain/moodTracker/controller/MoodTrackerController.java
  src/main/java/com/haru/api/domain/moodTracker/converter/MoodTrackerConverter.java
  src/main/java/com/haru/api/domain/moodTracker/dto/MoodTrackerResponseDTO.java
  src/main/java/com/haru/api/domain/moodTracker/service/MoodTrackerCommandServiceImpl.java
  src/main/java/com/haru/api/domain/moodTracker/service/MoodTrackerQueryServiceImpl.java
  src/main/java/com/haru/api/global/util/HashIdUtil.java
  src/test/resources/application-test.yml
Labels: ✨ Feature

#96 feat/#74: SNS 이벤트 생성 API 구현 완료
  .github/workflows/ci.yml
  src/main/java/com/haru/api/domain/snsEvent/controller/SnsEventController.java
  src/main/java/com/haru/api/domain/snsEvent/converter/SnsEventConverter.java
  src/main/java/com/haru/api/domain/snsEvent/dto/SnsEventRequestDTO.java
  src/main/java/com/haru/api/domain/snsEvent/dto/SnsEventResponseDTO.java
  src/main/java/com/haru/api/domain/snsEvent/entity/Participant.java
  src/main/java/com/haru/api/domain/snsEvent/entity/SnsEvent.java
  src/main/java/com/haru/api/domain/snsEvent/entity/Winner.java
  src/main/java/com/haru/api/domain/snsEvent/repository/ParticipantRepository.java
  src/main/java/com/haru/api/domain/snsEvent/repository/WinnerRepository.java
  src/main/java/com/haru/api/domain/snsEvent/service/SnsEventCommandService.java
  src/main/java/com/haru/api/domain/snsEvent/service/SnsEventCommandServiceImpl.java
  src/main/java/com/haru/api/domain/userWorkspace/repository/UserWorkspaceRepository.java
  src/main/java/com/haru/api/domain/workspace/entity/Workspace.java
  src/main/java/com/haru/api/global/apiPayload/code/status/ErrorStatus.java
Labels: ✨ Feature

#114 deploy 2.1 - ObjectMapper관련 API오류 해결
  src/main/java/com/haru/api/domain/user/converter/UserConverter.java
  src/main/java/com/haru/api/domain/user/dto/UserRequestDTO.java
  src/main/java/com/haru/api/domain/user/entity/User.java
  src/main/java/com/haru/api/domain/user/security/CustomAuthenticationProvider.java
  src/main/java/com/haru/api/domain/user/security/CustomUserDetailsService.java
  src/main/java/com/haru/api/domain/user/service/UserCommandServiceImpl.java
  src/main/java/com/haru/api/domain/workspace/dto/WorkspaceRequestDTO.java
  src/main/java/com/haru/api/global/apiPayload/code/status/ErrorStatus.java
Labels: 🌏 Deploy

#119 feat/#116: CORS 오류 해결
  src/main/java/com/haru/api/global/config/SecurityConfig.java
  src/main/java/com/haru/api/global/config/WebConfig.java
Labels: ✨ Feature

#120 feat/#41 workspace 초대 수락 기능 구현
  src/main/java/com/haru/api/domain/lastOpened/converter/UserDocumentLastOpenedConverter.java
  src/main/java/com/haru/api/domain/lastOpened/entity/UserDocumentId.java
  src/main/java/com/haru/api/domain/lastOpened/entity/UserDocumentLastOpened.java
  src/main/java/com/haru/api/domain/meeting/repository/MeetingRepository.java
  src/main/java/com/haru/api/domain/moodTracker/repository/MoodTrackerRepository.java
  src/main/java/com/haru/api/domain/snsEvent/repository/SnsEventRepository.java
  src/main/java/com/haru/api/domain/user/controller/UserController.java
  src/main/java/com/haru/api/domain/user/service/UserCommandService.java
  src/main/java/com/haru/api/domain/user/service/UserCommandServiceImpl.java
  src/main/java/com/haru/api/domain/workspace/controller/WorkspaceController.java
  src/main/java/com/haru/api/domain/workspace/converter/WorkspaceConverter.java
  src/main/java/com/haru/api/domain/workspace/dto/WorkspaceResponseDTO.java
  src/main/java/com/haru/api/domain/workspace/service/WorkspaceCommandService.java
  src/main/java/com/haru/api/domain/workspace/service/WorkspaceCommandServiceImpl.java
  src/main/java/com/haru/api/domain/workspaceInvitation/entity/WorkspaceInvitation.java
  src/main/java/com/haru/api/domain/workspaceInvitation/repository/WorkspaceInvitationRepository.java
Labels: ✨ Feature

#121 deploy 2.2 - CORS오류 해결
  src/main/java/com/haru/api/domain/lastOpened/converter/UserDocumentLastOpenedConverter.java
  src/main/java/com/haru/api/domain/lastOpened/entity/UserDocumentId.java
  src/main/java/com/haru/api/domain/lastOpened/entity/UserDocumentLastOpened.java
  src/main/java/com/haru/api/domain/meeting/repository/MeetingRepository.java
  src/main/java/com/haru/api/domain/moodTracker/repository/MoodTrackerRepository.java
  src/main/java/com/haru/api/domain/snsEvent/repository/SnsEventRepository.java
  src/main/java/com/haru/api/domain/user/controller/UserController.java
  src/main/java/com/haru/api/domain/user/service/UserCommandService.java
  src/main/java/com/haru/api/domain/user/service/UserCommandServiceImpl.java
  src/main/java/com/haru/api/domain/workspace/controller/WorkspaceController.java
  src/main/java/com/haru/api/domain/workspace/converter/WorkspaceConverter.java
  src/main/java/com/haru/api/domain/workspace/dto/WorkspaceRequestDTO.java
  src/main/java/com/haru/api/domain/workspace/dto/WorkspaceResponseDTO.java
  src/main/java/com/haru/api/domain/workspace/service/WorkspaceCommandService.java
  src/main/java/com/haru/api/domain/workspace/service/WorkspaceCommandServiceImpl.java
  src/main/java/com/haru/api/domain/workspaceInvitation/entity/WorkspaceInvitation.java
  src/main/java/com/haru/api/domain/workspaceInvitation/repository/WorkspaceInvitationRepository.java
  src/main/java/com/haru/api/global/config/MailConfig.java
  src/main/java/com/haru/api/global/config/SecurityConfig.java
  src/main/java/com/haru/api/global/config/WebConfig.java
  src/main/java/com/haru/api/infra/mail/SmtpEmailSender.java
  src/test/resources/application-test.yml
Labels: ✨ Feature

#113 feat/#103: AI Meeting 안건지 서비스로직 구분
  build.gradle
  src/main/java/com/haru/api/domain/meeting/entity/Keyword.java
  src/main/java/com/haru/api/domain/meeting/entity/Meeting.java
  src/main/java/com/haru/api/domain/meeting/entity/MeetingKeyword.java
  src/main/java/com/haru/api/domain/meeting/repository/KeywordRepository.java
  src/main/java/com/haru/api/domain/meeting/repository/MeetingKeywordRepository.java
  src/main/java/com/haru/api/domain/meeting/service/MeetingCommandServiceImpl.java
  src/main/java/com/haru/api/infra/api/client/ChatGPTClient.java
Labels: ✨ Feature

#127 feat/#124: SNS 이벤트 조회관련 API 구현
  src/main/java/com/haru/api/domain/snsEvent/controller/SnsEventController.java
  src/main/java/com/haru/api/domain/snsEvent/converter/SnsEventConverter.java
  src/main/java/com/haru/api/domain/snsEvent/dto/SnsEventRequestDTO.java
  src/main/java/com/haru/api/domain/snsEvent/dto/SnsEventResponseDTO.java
  src/main/java/com/haru/api/domain/snsEvent/repository/ParticipantRepository.java
  src/main/java/com/haru/api/domain/snsEvent/repository/SnsEventRepository.java
  src/main/java/com/haru/api/domain/snsEvent/repository/WinnerRepository.java
  src/main/java/com/haru/api/domain/snsEvent/service/SnsEventCommandService.java
  src/main/java/com/haru/api/domain/snsEvent/service/SnsEventCommandServiceImpl.java
Labels: ✨ Feature

#129 feat/#92: 워크스페이스 사이드바 최근 문서 조회 기능 구현
  src/main/java/com/haru/api/domain/meeting/repository/MeetingRepository.java
  src/main/java/com/haru/api/domain/moodTracker/repository/MoodTrackerRepository.java
  src/main/java/com/haru/api/domain/snsEvent/repository/SnsEventRepository.java
  src/main/java/com/haru/api/domain/workspace/controller/WorkspaceController.java
  src/main/java/com/haru/api/domain/workspace/converter/WorkspaceConverter.java
  src/main/java/com/haru/api/domain/workspace/dto/WorkspaceResponseDTO.java
  src/main/java/com/haru/api/domain/workspace/service/WorkspaceQueryService.java
  src/main/java/com/haru/api/domain/workspace/service/WorkspaceQueryServiceImpl.java
Labels: ✨ Feature

#135 deploy2.4 - 스웨거 CORS오류 해결
  src/main/java/com/haru/api/global/config/SecurityConfig.java
  src/main/java/com/haru/api/global/config/WebConfig.java
Labels: 🐞 Fix
