Repository HaRu-Developers/haru-springboot-api, pull requests merged in 2025-08, with the labels that each got.

#137 feat/#102: 문서가 조회될 때 마다 last opened 업데이트 하도록 구현
  src/main/java/com/haru/api/domain/lastOpened/entity/UserDocumentId.java
  src/main/java/com/haru/api/domain/lastOpened/entity/UserDocumentLastOpened.java
  src/main/java/com/haru/api/domain/lastOpened/repository/UserDocumentLastOpenedRepository.java
  src/main/java/com/haru/api/domain/lastOpened/service/UserDocumentLastOpenedService.java
  src/main/java/com/haru/api/domain/lastOpened/service/UserDocumentLastOpenedServiceImpl.java
  src/main/java/com/haru/api/domain/meeting/service/MeetingQueryServiceImpl.java
  src/main/java/com/haru/api/domain/moodTracker/service/MoodTrackerQueryServiceImpl.java
  src/main/java/com/haru/api/domain/snsEvent/controller/SnsEventController.java
  src/main/java/com/haru/api/domain/snsEvent/service/SnsEventCommandService.java
  src/main/java/com/haru/api/domain/snsEvent/service/SnsEventCommandServiceImpl.java
  src/main/java/com/haru/api/domain/snsEvent/service/SnsEventQueryService.java
  src/main/java/com/haru/api/domain/snsEvent/service/SnsEventQueryServiceImpl.java
  src/main/java/com/haru/api/global/annotation/LastOpenedAspect.java
  src/main/java/com/haru/api/global/annotation/TrackLastOpened.java
Labels: ✨ Feature

#152 feat/#149: 분위기 트래커 요청 및 응답 id string으로 변경
  src/main/java/com/haru/api/domain/moodTracker/dto/MoodTrackerRequestDTO.java
  src/main/java/com/haru/api/domain/moodTracker/dto/MoodTrackerResponseDTO.java
  src/main/java/com/haru/api/global/util/json/ToLongDeserializer.java
Labels: ✨ Feature

#147 feat/#146: workspaceId String으로 반환하고, mood tracker일때만 hashId 적용
  src/main/java/com/haru/api/domain/meeting/repository/MeetingRepository.java
  src/main/java/com/haru/api/domain/moodTracker/repository/MoodTrackerRepository.java
  src/main/java/com/haru/api/domain/snsEvent/repository/SnsEventRepository.java
  src/main/java/com/haru/api/domain/userWorkspace/dto/UserWorkspaceResponseDTO.java
  src/main/java/com/haru/api/domain/workspace/converter/WorkspaceConverter.java
  src/main/java/com/haru/api/domain/workspace/dto/WorkspaceResponseDTO.java
  src/main/java/com/haru/api/domain/workspace/service/WorkspaceQueryServiceImpl.java
  src/main/java/com/haru/api/global/util/ToLongDeserializer.java
Labels: ✨ Feature

#123 feat/#99: 인스타그램 계정 연동 API구현 및 Spring Security와 OAuth2.0을 이용한 구글 로그인 기능 구현
  build.gradle
  src/main/java/com/haru/api/domain/snsEvent/controller/SnsEventController.java
  src/main/java/com/haru/api/domain/snsEvent/converter/SnsEventConverter.java
  src/main/java/com/haru/api/domain/snsEvent/dto/SnsEventResponseDTO.java
  src/main/java/com/haru/api/domain/snsEvent/service/SnsEventCommandService.java
  src/main/java/com/haru/api/domain/snsEvent/service/SnsEventCommandServiceImpl.java
  src/main/java/com/haru/api/domain/user/entity/User.java
  src/main/java/com/haru/api/domain/user/repository/UserRepository.java
  src/main/java/com/haru/api/domain/user/security/googleOauth2/CustomOAuth2FailureHandler.java
  src/main/java/com/haru/api/domain/user/security/googleOauth2/CustomOAuth2SuccessHandler.java
  src/main/java/com/haru/api/domain/user/security/googleOauth2/CustomOauth2UserDetails.java
  src/main/java/com/haru/api/domain/user/security/googleOauth2/CustomOauth2UserService.java
  src/main/java/com/haru/api/domain/user/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/haru/api/domain/user/security/login/CustomAuthenticationProvider.java
  src/main/java/com/haru/api/domain/user/security/login/CustomDetailsService.java
  src/main/java/com/haru/api/domain/user/security/login/CustomUserDetailsService.java
  src/main/java/com/haru/api/domain/user/service/UserCommandService.java
  src/main/java/com/haru/api/domain/user/service/UserCommandServiceImpl.java
  src/main/java/com/haru/api/domain/workspace/dto/WorkspaceRequestDTO.java
  src/main/java/com/haru/api/domain/workspace/entity/Workspace.java
  src/main/java/com/haru/api/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/haru/api/global/config/RestTemplateConfig.java
  src/main/java/com/haru/api/global/config/SecurityConfig.java
  src/main/java/com/haru/api/infra/api/restTemplate/InstagramOauth2RestTemplate.java
  src/test/resources/application-test.yml
Labels: ✨ Feature

#159 feat/#157: SnsEvent API Id 타입 Long에서 String으로 변환 및 API 버저닝
  src/main/java/com/haru/api/domain/snsEvent/controller/SnsEventController.java
  src/main/java/com/haru/api/domain/snsEvent/dto/SnsEventResponseDTO.java
  src/main/java/com/haru/api/domain/snsEvent/service/SnsEventCommandServiceImpl.java
  src/main/java/com/haru/api/domain/snsEvent/service/SnsEventQueryServiceImpl.java
Labels: ✨ Feature

#160 feat/#148: 약관 조회 API 개발
  src/main/java/com/haru/api/domain/term/controller/TermController.java
  src/main/java/com/haru/api/domain/term/converter/TermConverter.java
  src/main/java/com/haru/api/domain/term/dto/TermResponseDTO.java
  src/main/java/com/haru/api/domain/term/entity/Term.java
  src/main/java/com/haru/api/domain/term/entity/enums/TermType.java
  src/main/java/com/haru/api/domain/term/repository/TermRepository.java
  src/main/java/com/haru/api/domain/term/service/TermService.java
  src/main/java/com/haru/api/domain/term/service/TermServiceImpl.java
  src/main/java/com/haru/api/domain/user/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/haru/api/global/apiPayload/code/status/ErrorStatus.java
Labels: ✨ Feature

#169 feat/#168: 회원가입 시 이메일 중복 검사 API 구현
  src/main/java/com/haru/api/domain/user/controller/UserController.java
  src/main/java/com/haru/api/domain/user/dto/UserRequestDTO.java
  src/main/java/com/haru/api/domain/user/dto/UserResponseDTO.java
  src/main/java/com/haru/api/domain/user/entity/enums/EmailStatus.java
  src/main/java/com/haru/api/domain/user/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/haru/api/domain/user/service/UserCommandService.java
  src/main/java/com/haru/api/domain/user/service/UserCommandServiceImpl.java
Labels: ✨ Feature

#174 feat/#173: 프론트엔드 테스트위한 모든 도메인 요청 CORS 허용
  src/main/java/com/haru/api/global/config/SecurityConfig.java
  src/main/java/com/haru/api/global/config/WebConfig.java
Labels: ✨ Feature

#178 deploy 2.8
  src/main/java/com/haru/api/domain/snsEvent/controller/SnsEventController.java
Labels: 🐞 Fix

#183 feat/#182: 구글 로그인중 redirect관련 uri(/favicon.ico) 인가처리에서 제외
  src/main/java/com/haru/api/domain/user/security/jwt/JwtAuthenticationFilter.java
Labels: ✨ Feature

#184 deploy 3.0
  src/main/java/com/haru/api/domain/user/security/jwt/JwtAuthenticationFilter.java
Labels: ✨ Feature

#189 feat/#186: 문서 업로드 및 썸네일 생성 기능 추가
  build.gradle
  src/main/java/com/haru/api/infra/s3/AmazonS3Manager.java
  src/main/java/com/haru/api/infra/s3/MarkdownFileUploader.java
  src/main/java/com/haru/api/infra/s3/MarkdownToPdfConverter.java
  src/main/java/com/haru/api/infra/s3/ThumbnailGeneratorService.java
Labels: ✨ Feature

#195 feat/#192: 기존 비밀번호 일치 확인 API 구현
  src/main/java/com/haru/api/domain/user/controller/UserController.java
  src/main/java/com/haru/api/domain/user/converter/UserConverter.java
  src/main/java/com/haru/api/domain/user/dto/UserRequestDTO.java
  src/main/java/com/haru/api/domain/user/dto/UserResponseDTO.java
  src/main/java/com/haru/api/domain/user/service/UserCommandService.java
  src/main/java/com/haru/api/domain/user/service/UserCommandServiceImpl.java
  src/main/java/com/haru/api/domain/user/service/UserQueryService.java
  src/main/java/com/haru/api/domain/user/service/UserQueryServiceImpl.java
Labels: ✨ Feature

#199 feat/#196: 문서 생성 시 last opened에 마지막으로 연 시간 null로 해서 추가하도록 구현
  src/main/java/com/haru/api/domain/meeting/service/MeetingCommandService.java
  src/main/java/com/haru/api/domain/meeting/service/MeetingCommandServiceImpl.java
  src/main/java/com/haru/api/domain/moodTracker/service/MoodTrackerCommandServiceImpl.java
  src/main/java/com/haru/api/domain/snsEvent/service/SnsEventCommandServiceImpl.java
Labels: ✨ Feature

#200 feat/#198: 구글 로그인 시 userId와 프로필 이미지 반환
  src/main/java/com/haru/api/domain/user/security/googleOauth2/CustomOAuth2SuccessHandler.java
Labels: ✨ Feature

#204 fix/#203: 문서 삭제 시 last opened 튜플 없어도 오류 발생 X
  src/main/java/com/haru/api/domain/meeting/service/MeetingCommandServiceImpl.java
  src/main/java/com/haru/api/domain/moodTracker/service/MoodTrackerCommandServiceImpl.java
  src/main/java/com/haru/api/domain/snsEvent/service/SnsEventCommandServiceImpl.java
Labels: 🐞 Fix

#212 feat/#211: 실시간 stt 병렬 처리 및 예외 처리 추가
  src/main/java/com/haru/api/infra/api/client/ChatGPTClient.java
  src/main/java/com/haru/api/infra/api/converter/SpeechSegmentConverter.java
  src/main/java/com/haru/api/infra/api/dto/SpeechSegmentResponseDTO.java
  src/main/java/com/haru/api/infra/websocket/AudioProcessingPipeline.java
  src/main/java/com/haru/api/infra/websocket/AudioProcessingQueue.java
  src/main/java/com/haru/api/infra/websocket/AudioSessionBuffer.java
  src/main/java/com/haru/api/infra/websocket/AudioWebSocketHandler.java
  src/main/java/com/haru/api/infra/websocket/processor/AIQuestionProcessor.java
  src/main/java/com/haru/api/infra/websocket/processor/ScoringProcessor.java
  src/main/java/com/haru/api/infra/websocket/processor/SpeechSegmentProcessor.java
  src/main/java/com/haru/api/infra/websocket/processor/WebSocketNotificationService.java
Labels: ✨ Feature

#188 deploy/#185: Fast API 배포 위해 network 설정
  .github/workflows/cd.yml
  deploy.sh
  docker-compose.yml
Labels: 🌏 Deploy

#229 feat/#130: 메인페이지 최근 문서 조회 기능 구현
  src/main/java/com/haru/api/domain/lastOpened/repository/UserDocumentLastOpenedRepository.java
  src/main/java/com/haru/api/domain/meeting/repository/MeetingRepository.java
  src/main/java/com/haru/api/domain/moodTracker/repository/MoodTrackerRepository.java
  src/main/java/com/haru/api/domain/snsEvent/repository/SnsEventRepository.java
  src/main/java/com/haru/api/domain/workspace/controller/WorkspaceController.java
  src/main/java/com/haru/api/domain/workspace/converter/WorkspaceConverter.java
  src/main/java/com/haru/api/domain/workspace/dto/WorkspaceResponseDTO.java
  src/main/java/com/haru/api/domain/workspace/service/WorkspaceQueryService.java
  src/main/java/com/haru/api/domain/workspace/service/WorkspaceQueryServiceImpl.java
Labels: ✨ Feature

#231 feat/#101 분위기 트래커 다운로드 API & #219 파일 및 썸네일 생성
  src/main/java/com/haru/api/domain/moodTracker/controller/MoodTrackerController.java
  src/main/java/com/haru/api/domain/moodTracker/dto/MoodTrackerResponseDTO.java
  src/main/java/com/haru/api/domain/moodTracker/entity/MoodTracker.java
  src/main/java/com/haru/api/domain/moodTracker/service/MoodTrackerCommandService.java
  src/main/java/com/haru/api/domain/moodTracker/service/MoodTrackerCommandServiceImpl.java
  src/main/java/com/haru/api/domain/moodTracker/service/MoodTrackerReportService.java
  src/main/java/com/haru/api/domain/moodTracker/service/MoodTrackerReportServiceImpl.java
  src/main/java/com/haru/api/domain/snsEvent/service/SnsEventCommandServiceImpl.java
  src/main/java/com/haru/api/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/haru/api/infra/redis/RedisReportConsumer.java
  src/main/java/com/haru/api/infra/s3/AmazonS3Manager.java
  src/main/java/com/haru/api/infra/s3/MarkdownFileUploader.java
  src/main/resources/templates/mood-tracker-report-template.html
Labels: ✨ Feature

#238 feat/#214: AI회의 Transcript 조회 기능 추가
  src/main/java/com/haru/api/domain/meeting/controller/MeetingController.java
  src/main/java/com/haru/api/domain/meeting/dto/MeetingResponseDTO.java
  src/main/java/com/haru/api/domain/meeting/service/MeetingQueryService.java
  src/main/java/com/haru/api/domain/meeting/service/MeetingQueryServiceImpl.java
  src/main/java/com/haru/api/infra/api/entity/AIQuestion.java
  src/main/java/com/haru/api/infra/api/entity/SpeechSegment.java
  src/main/java/com/haru/api/infra/api/repository/SpeechSegmentRepository.java
  src/main/java/com/haru/api/infra/websocket/AudioProcessingPipeline.java
  src/main/java/com/haru/api/infra/websocket/processor/AIQuestionProcessor.java
Labels: ✨ Feature

#244 fix: 배포 스크립트 수정
  build.gradle
  deploy.sh
Labels: 🐞 Fix

#245 deploy 3.5
  build.gradle
  deploy.sh
  src/main/java/com/haru/api/domain/moodTracker/service/MoodTrackerMailServiceImpl.java
  src/test/resources/application-test.yml
Labels: 🌏 Deploy

#247 fix/#246: SNS 이벤트 생성 중 PDF, Word파일 생성시에 폰트 경로 문제 해결
  src/main/java/com/haru/api/domain/snsEvent/service/SnsEventCommandServiceImpl.java
Labels: 🐞 Fix

#248 deploy 3.6
  src/main/java/com/haru/api/domain/snsEvent/service/SnsEventCommandServiceImpl.java
Labels: ✨ Feature

#253 feat/#252: 구글 로그인 후 프론트엔드 리다이렉트 URI 수정
  src/main/java/com/haru/api/domain/user/security/googleOauth2/CustomOAuth2FailureHandler.java
  src/main/java/com/haru/api/domain/user/security/googleOauth2/CustomOAuth2SuccessHandler.java
  src/test/resources/application-test.yml
Labels: ✨ Feature

#258 feat/#257: 회원가입 후 로그인까지 진행하는 API 구현
  src/main/java/com/haru/api/domain/user/controller/UserController.java
  src/main/java/com/haru/api/domain/user/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/haru/api/domain/user/service/UserCommandService.java
  src/main/java/com/haru/api/domain/user/service/UserCommandServiceImpl.java
Labels: ✨ Feature

#294 fix/#292: 회원가입 후 로그인 시 token 없으면 일반 회원가입 실행되도록 수정
  src/main/java/com/haru/api/domain/user/service/UserCommandServiceImpl.java
Labels: 🐞 Fix

#296 Feat/#236 mood tracker sync
  src/main/java/com/haru/api/domain/moodTracker/controller/MoodTrackerController.java
  src/main/java/com/haru/api/domain/moodTracker/dto/MoodTrackerRequestDTO.java
  src/main/java/com/haru/api/domain/moodTracker/repository/CheckboxChoiceRepository.java
  src/main/java/com/haru/api/domain/moodTracker/repository/MultipleChoiceRepository.java
  src/main/java/com/haru/api/domain/moodTracker/service/MoodTrackerCommandServiceImpl.java
  src/main/java/com/haru/api/domain/moodTracker/service/MoodTrackerReportService.java
  src/main/java/com/haru/api/domain/moodTracker/service/MoodTrackerReportServiceImpl.java
  src/main/java/com/haru/api/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/haru/api/infra/api/client/ChatGPTClient.java
Labels: ✨ Feature, 🔨 Refactor

#298 feat/#297: 분위기 트래커 베이스 정보 조회 API
  src/main/java/com/haru/api/domain/moodTracker/controller/MoodTrackerController.java
  src/main/java/com/haru/api/domain/moodTracker/converter/MoodTrackerConverter.java
  src/main/java/com/haru/api/domain/moodTracker/service/MoodTrackerQueryService.java
  src/main/java/com/haru/api/domain/moodTracker/service/MoodTrackerQueryServiceImpl.java
Labels: ✨ Feature

#299 fix/#292: 회원가입 시 user document 추가 안되는 오류 수정
  src/main/java/com/haru/api/domain/user/service/UserCommandServiceImpl.java
  src/main/java/com/haru/api/domain/workspace/service/WorkspaceCommandServiceImpl.java
Labels: 🐞 Fix

#300 feat/#285: SNS 이벤트 제목 수정 시 S3의 다운로드 문서 제목 및 문서내 제목 수정, S3의 썸네일 이미지 수정
  src/main/java/com/haru/api/domain/snsEvent/service/SnsEventCommandServiceImpl.java
Labels: ✨ Feature

#306 fix/#305: meeting, sns event, mood tracker 생성/삭제 오류 수정
  src/main/java/com/haru/api/domain/moodTracker/service/MoodTrackerCommandServiceImpl.java
  src/main/java/com/haru/api/domain/snsEvent/service/SnsEventCommandServiceImpl.java
  src/main/java/com/haru/api/domain/workspace/entity/Workspace.java
Labels: 🐞 Fix

#308 feat/#286: ai meeting download doctype
  src/main/java/com/haru/api/domain/meeting/controller/MeetingController.java
  src/main/java/com/haru/api/domain/meeting/entity/Meeting.java
  src/main/java/com/haru/api/domain/meeting/service/MeetingCommandServiceImpl.java
  src/main/java/com/haru/api/domain/meeting/service/MeetingQueryService.java
  src/main/java/com/haru/api/domain/meeting/service/MeetingQueryServiceImpl.java
  src/main/java/com/haru/api/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/haru/api/infra/s3/MarkdownFileUploader.java
  src/main/java/com/haru/api/infra/s3/MarkdownToPdfConverter.java
  src/main/java/com/haru/api/infra/s3/MarkdownToWordConverter.java
Labels: ✨ Feature

#313 feat/#311: 워크스페이스에 연동된 인스타그램 계정 조회하는 API 구현
  src/main/java/com/haru/api/domain/snsEvent/controller/SnsEventController.java
  src/main/java/com/haru/api/domain/snsEvent/converter/SnsEventConverter.java
  src/main/java/com/haru/api/domain/snsEvent/dto/SnsEventResponseDTO.java
  src/main/java/com/haru/api/domain/snsEvent/service/SnsEventQueryService.java
  src/main/java/com/haru/api/domain/snsEvent/service/SnsEventQueryServiceImpl.java
Labels: ✨ Feature

#316 fix/#315: workspace 생성/수정 기능 오류 수정
  src/main/java/com/haru/api/domain/workspace/converter/WorkspaceConverter.java
  src/main/java/com/haru/api/domain/workspace/service/WorkspaceCommandServiceImpl.java
Labels: 🐞 Fix

#317 deploy 4.6
  src/main/java/com/haru/api/domain/lastOpened/service/UserDocumentLastOpenedService.java
  src/main/java/com/haru/api/domain/lastOpened/service/UserDocumentLastOpenedServiceImpl.java
  src/main/java/com/haru/api/domain/moodTracker/service/MoodTrackerCommandServiceImpl.java
  src/main/java/com/haru/api/domain/moodTracker/service/MoodTrackerReportServiceImpl.java
  src/main/java/com/haru/api/domain/snsEvent/service/SnsEventCommandServiceImpl.java
  src/main/java/com/haru/api/domain/workspace/converter/WorkspaceConverter.java
  src/main/java/com/haru/api/domain/workspace/service/WorkspaceCommandServiceImpl.java
Labels: 🌏 Deploy

#319 fix/#318: workspace 오류 수정
  src/main/java/com/haru/api/domain/userWorkspace/dto/UserWorkspaceResponseDTO.java
  src/main/java/com/haru/api/domain/userWorkspace/service/UserWorkspaceQueryServiceImpl.java
  src/main/java/com/haru/api/domain/workspace/entity/Workspace.java
  src/main/java/com/haru/api/domain/workspace/service/WorkspaceCommandServiceImpl.java
Labels: 🐞 Fix

#320 deploy 4.7
  src/main/java/com/haru/api/domain/userWorkspace/dto/UserWorkspaceResponseDTO.java
  src/main/java/com/haru/api/domain/userWorkspace/service/UserWorkspaceQueryServiceImpl.java
  src/main/java/com/haru/api/domain/workspace/entity/Workspace.java
  src/main/java/com/haru/api/domain/workspace/service/WorkspaceCommandServiceImpl.java
Labels: 🌏 Deploy

#323 fix/#322: SNS 이벤트 및 분위기 트레커 문서 조회 시 수정시간 기준 최신순으로 정렬되어 조회되도록 수정
  src/main/java/com/haru/api/domain/moodTracker/repository/MoodTrackerRepository.java
  src/main/java/com/haru/api/domain/moodTracker/service/MoodTrackerQueryServiceImpl.java
  src/main/java/com/haru/api/domain/snsEvent/repository/SnsEventRepository.java
  src/main/java/com/haru/api/domain/snsEvent/service/SnsEventQueryServiceImpl.java
Labels: 🐞 Fix

#326 fix/#325: Meeting 삭제시 연관된 speechSegment도 삭제되도록 추가
  src/main/java/com/haru/api/domain/meeting/service/MeetingCommandServiceImpl.java
Labels: 🐞 Fix

#328 fix/#327: Meeting proceeding 수정시 파일 갱신 오류 해결
  src/main/java/com/haru/api/domain/meeting/service/MeetingCommandServiceImpl.java
Labels: 🐞 Fix

#329 deploy 4.9
  src/main/java/com/haru/api/domain/meeting/service/MeetingCommandServiceImpl.java
Labels: 🌏 Deploy

#332 deploy 4.10
  src/main/java/com/haru/api/domain/lastOpened/service/UserDocumentLastOpenedServiceImpl.java
  src/main/java/com/haru/api/domain/moodTracker/controller/MoodTrackerController.java
  src/main/java/com/haru/api/domain/moodTracker/service/MoodTrackerQueryServiceImpl.java
Labels: 🌏 Deploy

#335 refactor/#334: 이메일 형식 검증
  src/main/java/com/haru/api/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/haru/api/infra/mail/SmtpEmailSender.java
Labels: 🔨 Refactor

#338 refactor/#336: 설문 마감일시에 실패시 retry 전략
  src/main/java/com/haru/api/domain/moodTracker/controller/MoodTrackerController.java
  src/main/java/com/haru/api/domain/moodTracker/service/MoodTrackerCommandServiceImpl.java
  src/main/java/com/haru/api/infra/redis/RedisReportConsumer.java
Labels: 🔨 Refactor

#340 feat/#337: 인스타그램 redirect-uri 한개 더 추가 및 인스타그램 API 연동 시 redirect-uri동적으로 바꾸는 기능 추가
  src/main/java/com/haru/api/domain/snsEvent/controller/SnsEventController.java
  src/main/java/com/haru/api/domain/snsEvent/entity/enums/InstagramRedirectType.java
  src/main/java/com/haru/api/domain/snsEvent/service/SnsEventCommandService.java
  src/main/java/com/haru/api/domain/snsEvent/service/SnsEventCommandServiceImpl.java
  src/main/java/com/haru/api/infra/api/restTemplate/InstagramOauth2RestTemplate.java
  src/test/resources/application-test.yml
Labels: ✨ Feature

#341 refactor/#336: 설문 마감일시에 실패시 retry 전략
  src/main/java/com/haru/api/domain/moodTracker/service/MoodTrackerCommandServiceImpl.java
  src/main/java/com/haru/api/infra/redis/RedisReportConsumer.java
  src/main/java/com/haru/api/infra/redis/ReportWorker.java
Labels: 🔨 Refactor

#343 Refactor/#336 mood tracker retry
  src/main/java/com/haru/api/infra/redis/RedisReportConsumer.java
  src/main/java/com/haru/api/infra/redis/ReportWorker.java
Labels: 🔨 Refactor

#349 feat/#348: ai meeting thumbnail keyname lastopened
  src/main/java/com/haru/api/domain/meeting/service/MeetingCommandServiceImpl.java
Labels: ✨ Feature

#354 fix/#353: SNS 이벤트 인스타그램 API 댓글 제한 해제 및 SNS 이벤트 생성 시 여러개 키워드 포함할 수 있도록 수정
  src/main/java/com/haru/api/domain/snsEvent/service/SnsEventCommandServiceImpl.java
Labels: 🐞 Fix

#355 deploy 4.16
  src/main/java/com/haru/api/domain/snsEvent/service/SnsEventCommandServiceImpl.java
Labels: 🐞 Fix
